### PR TITLE
added write_and_read()

### PR DESCRIPTION
**Pull request by eringerli**
This method adds a wrapper for transfer() with CS-pin and transaction management

### CODE REVIEW

**Comment by eringerli** [comment]
Please publish you clang-format file somewhere and include a remark in the pull-request guide, so people can verify the format before it is rejected by your CI flow.

**Comment by caternuson** [comment]
This might be a dupe of #49?

clang formatting covered here:
https://learn.adafruit.com/the-well-automated-arduino-library/formatting-with-clang-format

**Comment by eringerli** [comment]
Kind of, but write_and_read() does it in Adafruit_BusIO. I can't see why it wasn't there in the first place. I'm surely not the only one which wants to use a well done lib which takes care of all the nitty gritty stuff (setting up/storing/reset the speeds and CS, asserting it, etc) but with the semantics of SPIClass::transfer().

-- 
 

Mit freundlichem Gruss

Christian Riggenbach

Am 31. Dezember 2021 18:18:05 MEZ schrieb Carter Nelson ***@***.***>:

**Comment by ladyada** [comment]
hiya, we use the clang-format defaults, fyi!
thanks for the PR :)

**Comment by eringerli** [comment]
Thanks! Even working on a free day 😁

**Pull request merged**
