### PR TITLE
combined read/write methods for an improvement in performance

### PR DESCRIPTION
**Pull request by eringerli**
If the code doesn't run on an 8bit-AVR, the data is prepared by combining the reads and writes into one buffer, which is then transfered as one transaction on the bus. A constant decides if the buffer is allocated on the stack or from the heap, further reducing the overhead for small reads and writes by reducing heap thrashing. This is a tradeof between RAM/CPU and bus speed: on the 'bigger' arduino platforms the CPU is a lot faster than the SPI and there is a lot of RAM avaible, so using more RAM/CPU cycles and then letting the DMA do its work is the way to go.

This also allows for the use of chunked `transfer()` in all cases, which gives an improvement of about 50% over bytewise writes. This is for all supported platforms except 8bit AVRs, which are specifically `#if`'d out. The special case for the ESP32 is therefore removed and ARM M0/M4, ESP8266, teensy etc should profit of this improvement too, without special casing each platform by using non standard arduino core extensions.

All in all, this results in a performance improvement for 32bit platforms of about 65% over bytewise transfers in typical usecases (tested with an ESP32 with Adafruit_BusIO_Register).

## Logic analyser trace
These are two traces of the data read out of a LIS3MDL over SPI with 10Mhz data rate.

### Before this PR (special cased ESP32 without combined buffer)
Screenshot_20220418_184113
### After this PR (no special case, but with combined buffer)
Screenshot_20220418_185123
### Using bytewise transfer on an ESP32
Screenshot_20220418_184353

### CODE REVIEW

**Comment by eringerli** [comment]
This is based on current master, If you merge #92 and/or #93, I'll rebase it.

**Comment by eringerli** [comment]
The more I think about this, the more I come to the conclusion, that without an upper limit, this effectively doubles the memory requirement of all transfers. This isn't a big deal for small ones like in BusIO, but breaks big ones as in GFX. I'll rewrite this to only get used in small transfers.

**Comment by eringerli** [comment]
I'll currently developing a version which does chunked transfers with a buffer on the stack. I think, that one is much more sensible, as it also works on really large transfers.

**Comment by ladyada** [comment]
sounds good, its in a place now we can do such things!

**Pull request closed without merging**
